Carts/Carts/Controllers/ManageOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Carts.Controllers
{
    public class ManageOrderController : Controller
    {
        // GET: ManageOrder
        public ActionResult Index()
        {
            using (Models.CartsEntities db = new Models.CartsEntities())
            {
                //取得Order中所有資料
                var result = (from s in db.Orders
                              select s).ToList();

                return View(result);
            }
        }

        public ActionResult Details(int id)
        {
            using (Models.CartsEntities db = new Models.CartsEntities())
            {
                //取得OrderId為傳入id的所有商品列表
                var result = (from s in db.OrderDetails
                              where s.OrderId == id
                              select s).ToList();

                if (result.Count == 0)
                {   //如果商品數目為零，代表該訂單異常(無商品)，則導回商品列表
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(result);
                }
            }
        }

        public ActionResult SerachByUserName(string UserName)
        {
            //儲存查詢出來的UserId
            string searchUserId = null;
            using (Models.UserEntities db = new Models.UserEntities())
            {   //查詢目前網站使用者暱稱符合UserName的UserId
                searchUserId = (from s in db.AspNetUsers
                                where s.UserName == UserName
                                select s.Id).FirstOrDefault();
            }
            //如果有存在UserId
            if (!String.IsNullOrEmpty(searchUserId))
            {   //則將此UserId的所有訂單找出
                using (Models.CartsEntities db = new Models.CartsEntities())
                {
                    var result = (from s in db.Orders
                                  where s.UserId == searchUserId
                                  select s).ToList();

                    //回傳 結果 至Index()的View
                    return View("Index", result);
                }
            }
            else
            {   //回傳 空結果 至Index()的View
                return View("Index", new List<Models.Order>());
            }

        }

        



    }
}

Carts/Carts/Views/ManageOrder/Details.cshtml
@model IEnumerable<Carts.Models.OrderDetail>

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@String.Format("訂單編號{0}商品列表", this.Model.First().Id)</h2>
<hr />
@Html.ActionLink("回商品列表", "Index", new { }, new { @class = "btn btn-default" })
<table class="table">
    <tr>
        <th>商品名稱</th>
        <th>商品價格</th>
        <th>購買數量</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
        </tr>
    }

</table>
@Html.ActionLink("回商品列表", "Index", new { }, new { @class = "btn btn-default" })

Carts/Carts/Views/ManageOrder/Index.cshtml
@model IEnumerable<Carts.Models.Order>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>訂單列表</h2>

@using (Html.BeginForm("SerachByUserName", "ManageOrder"))
{
    @Html.TextBox("UserName", null, new { @class = "btn-info" })
    <input type="submit" value="搜尋" class="btn btn-default" />
}


<table class="table">
    <tr>
        <th>購買會員</th>
        <th>收貨人姓名</th>
        <th>收貨人電話</th>
        <th>收貨人住址</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.GetUrderName()
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RecieverName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RecieverPhone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RecieverAddress)
            </td>
            <td>
                @Html.ActionLink("商品明細", "Details", new { id = item.Id }
                 , new { @class = "btn btn-default" })
            </td>
        </tr>
    }
</table>