Carts/Carts/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Carts.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        public ActionResult Index()
        {
            return View();
        }

        //取得目前購物車頁面
        public ActionResult GetCart()
        {
            return PartialView("_CartPartial");
        }

        //以id加入Product至購物車，並回傳購物車頁面
        public ActionResult AddToCart(int id)
        {
            var currentCart = Models.Cart.Operation.GetCurrentCart();
            currentCart.AddProduct(id);
            return PartialView("_CartPartial");
        }

        //以id移除購物車Product，並回傳購物車頁面
        public ActionResult RemoveFromCart(int id)
        {
            var currentCart = Models.Cart.Operation.GetCurrentCart();
            currentCart.RemoveProduct(id);
            return PartialView("_CartPartial");
        }

        //清空購物車，並回傳購物車頁面
        public ActionResult ClearCart()
        {
            var currentCart = Models.Cart.Operation.GetCurrentCart();
            currentCart.ClearCart();
            return PartialView("_CartPartial");
        }


    }
}

Carts/Carts/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace Carts.Controllers
{
    public class OrderController : Controller
    {
        // GET: Order
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Models.OrderModel.Ship postback)
        {
            if (this.ModelState.IsValid)
            {   //取得目前購物車
                var currentcart = Models.Cart.Operation.GetCurrentCart();

                //取得目前登入使用者Id
                var userId = HttpContext.User.Identity.GetUserId();

                using (Models.CartsEntities db = new Models.CartsEntities())
                {
                    //建立Order物件
                    var order = new Models.Order()
                    {
                        UserId = userId,
                        RecieverName = postback.RecieverName,
                        RecieverPhone = postback.RecieverPhone,
                        RecieverAddress = postback.RecieverAddress
                    };
                    //加其入Orders資料表後，儲存變更
                    db.Orders.Add(order);
                    db.SaveChanges();

                    //取得購物車中OrderDetai物件
                    var orderDetails = currentcart.ToOrderDetailList(order.Id);

                    //將其加入OrderDetails資料表後，儲存變更
                    db.OrderDetails.AddRange(orderDetails);
                    db.SaveChanges();
                }
                return RedirectToAction("MyOrder");
            }
            return View(postback);
        }

        public ActionResult MyOrder()
        {
            //取得目前登入使用者Id
            var userId = HttpContext.User.Identity.GetUserId();

            using (Models.CartsEntities db = new Models.CartsEntities())
            {
                var result = (from s in db.Orders
                              where s.UserId == userId
                              select s).ToList();

                return View(result);
            }
        }

        public ActionResult MyOrderDetail(int id)
        {
            using (Models.CartsEntities db = new Models.CartsEntities())
            {
                var result = (from s in db.OrderDetails
                              where s.OrderId == id
                              select s).ToList();

                if (result.Count == 0)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(result);
                }
            }
        }



    }
}

Carts/Carts/Views/Shared/_CartPartial.cshtml
@{
    //取得當前購物車所有內容
    var currentCart = Carts.Models.Cart.Operation.GetCurrentCart();
}
<a id="CartDropDown" class="dropdown-toggle" data-toggle="dropdown">
    @String.Format("共{0}元 ({1})", currentCart.TotalAmount, currentCart.Count)
    <span class="caret"></span>
</a>
<ul class="dropdown-menu Cart" role="menu" aria-labelledby="CartDropDown">
    @if (currentCart.Count > 0)
    {
        foreach (var cartitem in currentCart)
        {
            //依序輸出 : <li><a>可愛橡皮擦 <span>50元 X 2</span></a></li>
            <li class="col-xs-12">
                <span class="col-xs-9">@cartitem.Name @cartitem.Price.ToString("0.0") 元 X @cartitem.Quantity </span>
                <span class="btn btn-danger col-xs-2" onclick="RemoveFromCart('@cartitem.Id')">
                    X
                </span>
            </li>
        }
        <li class="divider"></li>
        <li>
            <div id="CartButtons" class="col-xs-12">
                <a class="btn btn-success text-center col-xs-5" href="@Url.Action("Index","Order",new { })">
                    結帳去
                </a>
                <a class="btn btn-danger text-center  col-xs-5" onclick="ClearCart()">清空</a>
            </div>
        </li>
    }
    else
    {
        <li><a class="btn btn-default text-center" href="#">購物車無任何商品</a></li>
    }

</ul>

Carts/Carts/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -咖啡豆專賣店</title>
    <style>
        ul.Cart li {
            width: 260px;
        }

            ul.Cart li span {
                margin: 2px;
            }

        #CartButtons {
            display: inline-block;
        }

            #CartButtons > a {
                margin: 6px;
            }
    </style>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @* 購物車Js *@
    <script type="text/javascript">
        //網頁載入完成時執行之function
        $(document).ready(function () {
            console.log("ready!");
        });

        //加入編號為productId的商品進購物車
        function AddToCart(productId) {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("AddToCart", "Cart")',
                data: { id: productId }
            })
                .done(function (msg) {
                    //將回傳的購物車頁面 填入 li#Cart
                    $('li#Cart').html(msg);
                });
        }

        //移除購物車內商品
        function RemoveFromCart(productId) {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("RemoveFromCart", "Cart")',
                data: { id: productId }
            })
                .done(function (msg) {
                    //將回傳的購物車頁面 填入 li#Cart
                    $('li#Cart').html(msg);
                });
        }

        //清空購物車內所有商品
        function ClearCart() {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("ClearCart", "Cart")',
                data: {}
            })
            .done(function (msg) {
                //將回傳的購物車頁面 填入 li#Cart
                $('li#Cart').html(msg);
            });
        }
    </script>
</head>





<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("咖啡豆購物網站", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "Home")</li>
                    @*<li>@Html.ActionLink("咖啡豆專區", "Index", "AllProducts")</li>*@
                    @*<li>@Html.ActionLink("商品管理", "Index", "Product")</li>
                    <li>@Html.ActionLink("會員管理", "Index", "ManageUser")</li>
                    <li>@Html.ActionLink("訂單管理", "Index", "ManageOrder")</li>*@
                    <li id="Cart">
                        @Html.Partial("_CartPartial")
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">

        @RenderBody()
        <hr />
        <footer id="footer">

            <div class="copyright">
                &copy; The Antique Cave
            </div>
        </footer>
    </div>
</body>

</html>
<!-- Scripts -->
<script src="/assets/js/jquery.min.js"></script>
<script src="/assets/js/jquery.scrollex.min.js"></script>
<script src="/assets/js/skel.min.js"></script>
<script src="/assets/js/util.js"></script>
<script src="/assets/js/main.js"></script>